name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Setup Go environment
      uses: actions/setup-go@v4.0.1
      with:
        go-version: '1.20'

    - name: Get dependencies
      run: go mod download

    - name: Build
      run: go build pull-updater.go

    - name: GH Release
      uses: softprops/action-gh-release@v0.1.15
      with:
          files: pull-updater
      